[build]
  environment = { 
    VITE_FIREBASE_API_KEY="AIzaSyClw98Knx1ocHvFWsTj_hJ5qtQT0XSB5AU"
    VITE_FIREBASE_AUTH_DOMAIN="pokedexmon-464c6.firebaseapp.com"
    VITE_FIREBASE_PROJECT_ID="pokedexmon-464c6"
    VITE_FIREBASE_STORAGE_BUCKET="pokedexmon-464c6.appspot.com"
    VITE_FIREBASE_MESSAGING_SENDER_ID="736331360700"
    VITE_FIREBASE_APP_ID="1:736331360700:web:d84ec574a647b38df1a3b9"
    VITE_FIREBASE_MEASUREMENT_ID="G-7F8HEYW8YP""
  }