export * from './GlobalsStyles.css'
export * from './HomePage/'
export * from './PageSearch/'
export * from './PagePokemon/'
export * from './CardPokemon.css'
export * from './Header.css'
export * from './Login.css'
export * from './ModalAvatares.css'
